#+title: Marlin's personal website

This repository contains the source code for my personal website, which is served at [[https://www.marlinstrub.com]].

* Instructions

** Development

The site can be served locally via Emacs using [[https://github.com/skeeto/emacs-web-server/tree/master][simple-httpd]]. I have tested this with the following [[https://github.com/radian-software/straight.el][straight]] recipe:

#+begin_src elisp
(use-package simple-httpd
  :straight (simple-httpd :host github :repo "skeeto/emacs-web-server"))
#+end_src

First run [[file:build.sh][build.sh]] and then ~M-x httpd-serve-directory~. Navigate to the ~public~ folder when asked for a directory to serve. By default, this will serve the directory at [[http://localhost:8080/]].

** Publication

This repository contains the file [[file:.github/workflows/publish.yml][.github/workflows/publish.yml]], which instructs GitHub to generate the site using [[file:build.sh][build.sh]] whenever a commit is pushed to the ~main~ branch. This script will place the generated files in a directory called ~public~ and copy the files in this directory to a branch called ~gh-pages~. This branch is then hosted by GitHub.

* Acknowledgements

The css stylesheet is a modified version of Nicolas Rougier's [[https://www.labri.fr/perso/nrougier/GTD/GTD.css][GTD.css]]. The approach for [[https://youtu.be/AfkrzFodoNw][generating the website with Emacs]] and [[https://youtu.be/za99DwdZEyg][hosting it on GitHub pages]] was inspired by David Wilson's linked tutorials.
