#+include: ../elements/title.org
#+include: ../elements/navigation.org

* Your guide to using polymorphism in robotics

Polymorphism allows one interface to stand in for many types. This can be useful in various scenarios but I think it is especially powerful when prototyping because it allows you to try out different approaches and implement different behaviors simply by swapping the type behind the interface.

If your C++ education was similar to mine, then you thought for a while that polymorphism in C++ basically /is/ public inheritance. But there are several other mechanisms that enable polymorphism in C++, and I think it's worth knowing what their trade-offs are.

This post looks at these mechanisms from the perspective of someone that aims to write code that is both /flexible/, i.e., allows you to prototype and adapt to changing requirements, and /maintainable/, i.e., localizes complexity and minimizes dependencies (as opposed to, e.g., someone that aims to maximize performance).

** Two questions to guide you

There are two questions that I find generally useful in determining what the right mechanism is for a given use-case. Let's start with the simpler one:

/“Do I need run-time polymorphism?”/

Another way to ask this is “Will it be necessary to select the approach while my stack is running (or launching)?” If yes then you have to use run-time polymorphism. Otherwise you should probably prefer compile-time polymorphism because the compiler is great at helping you find bugs.

The second question is

/“Do I want to satisfy the open-closed principle for types or for operations?”/

Another way to ask this is “Will I more often add completely new approaches (i.e., add new types) or extend the initial interface (i.e., add new operations)?” Cleverly-written libraries like [[https://www.boost.org/doc/libs/latest/libs/openmethod/doc/html/openmethod/motivation.html][Boost.OpenMethod]] allow you to both add new types and new operations without modifying existing code, but it requires considerable machinery and I find they add significant cognitive load -- no free lunch*.

The table below summarizes the rest of this post.

|            | Run-time (dynamic)                 | Compile-time (static)       |
|------------+------------------------------------+-----------------------------|
| *Types*      | Inheritance or type erasure        | Concepts (CRTP pre C++20)   |
| *Operations* | Visitors, variants or tagged union | Overload set / tag dispatch |

** Public inheritance

- Strengths: Satisfies the OCP for types, is familiar to most, requires virtually no boilerplate (pun intended)
- Drawbacks: Violates the OCP for operations, forces reference semantics

This is your classic interface base class that most people are familiar with:

#+header: :transclude [[file:code/blog-polymorphism-in-robotics_public-inheritance-0.cpp]]
#+begin_src cpp :flags "-std=c++23" :includes '(<print> <memory>) :noweb yes :results verbatim :exports both
struct control{}; // Dummy type to represent the control input of your robot
struct state{};   // Dummy type to represent the state of your robot

struct controller_base {
  virtual auto advance(const state& state) const -> control = 0;
};

struct controller_a : public controller_base {
  auto advance(const state& state) const -> control override {
    std::println("controller_a::advance"); return {};
  }
};

struct controller_b : public controller_base {
  auto advance(const state& state) const -> control override {
    std::println("controller_b::advance"); return {};
  };
};

int main() {
  std::unique_ptr<controller_base> controller;
  if (/* runtime_condition_for_controller_a == */ true) {
    controller = std::make_unique<controller_a>();
    controller->advance();
  }
  if (/* runtime_condition_for_controller_b == */ true) {
    controller = std::make_unique<controller_b>();
    controller->advance();
  }
}
#+end_src

#+RESULTS:
: controller_a::advance
: controller_b::advance

Ideally you find a single (probably learned) controller that can handle every motion your system must execute. Every robotics stack I've ever worked with had multiple controllers, each geared for different purposes (e.g., trotting vs. walking up stairs). Public inheritance allows you to switch these controllers at runtime. It also allows you to try out completely new controllers if you're unsatisfied with the performance of an existing controller and to extend the capabilities of your robot by adding a completely new controller.

#+header: :transclude [[file:code/blog-polymorphism-in-robotics_public-inheritance-1.cpp]]
#+header: :diff-base [[file:code/blog-polymorphism-in-robotics_public-inheritance-0.cpp]]
#+begin_src cpp :flags "-std=c++23" :includes '(<print> <memory>) :noweb yes :results verbatim :exports both
struct control{}; // Dummy type to represent the control of your robot
struct state{};   // Dummy type to represent the state of your robot

struct controller_base {
  virtual auto advance(const state& state) const -> control = 0;
};

struct controller_a : public controller_base {
  auto advance(const state& state) const -> control override {
    std::println("controller_a::advance"); return {};
  }
};

struct controller_b : public controller_base {
  auto advance(const state& state) const -> control override {
    std::println("controller_b::advance"); return {};
  };
};

struct controller_c : public controller_base {
  auto advance(const state& state) const -> control override {
    std::println("controller_c::advance"); return {};
  };
};

int main() {
  std::unique_ptr<controller_base> controller;
  if (/* runtime_condition_for_controller_a == */ true) {
    controller = std::make_unique<controller_a>();
    controller->advance();
  }
  if (/* runtime_condition_for_controller_b == */ true) {
    controller = std::make_unique<controller_b>();
    controller->advance();
  }
  if (/* runtime_condition_for_controller_c == */ true) {
    controller = std::make_unique<controller_c>();
    controller->advance();
  }
}
#+end_src

#+RESULTS:
: controller_a::advance
: controller_b::advance
: controller_c::advance

One drawback is that adding operations to the interface, requires you to change every implementation of it. Another drawback is that it forces reference semantics. A third drawback is that in practice it often results in violation of the interface segregation principle.

Let's say one of your controllers is a PID controller and a first-time deployment reveals that in some scenarios you need the be able to reset the integral wind-up of it. If you've chosen public inheritance as your polymorphism mechanism, then it is not enough to implement a ~reset~ method in the PID controller, you also need to implement it in the base class and, worse, in the controller that is not a PID controller and maybe doesn't hold state, so there's nothing the ~reset~ method can sensibly do.

#+header: :transclude [[file:code/blog-polymorphism-in-robotics_public-inheritance-2.cpp]]
#+header: :diff-base [[file:code/blog-polymorphism-in-robotics_public-inheritance-1.cpp]]
#+begin_src cpp :flags "-std=c++23" :includes '(<print> <memory>) :noweb yes :results verbatim :exports both
struct control{}; // Dummy type to represent the control of your robot
struct state{};   // Dummy type to represent the state of your robot

struct controller_base {
  virtual auto advance(const state &state) const -> control = 0;
  virtual auto reset() -> void = 0; // This change is only needed because of the mechanism
};

struct controller_a : public controller_base {
  auto advance(const state& state) const -> control override {
    std::println("controller_a::advance"); return {};
  }
  auto reset() -> void override {
    std::println("controller_a::reset"); // Resets the integrator (the change you want)
  }
};

struct controller_b : public controller_base {
  auto advance(const state& state) const -> control override {
    std::println("controller_b::advance"); return {};
  };
  auto reset() -> void override {
    std::println("controller_b::reset"); // This change is only needed because of the mechanism
  }
};

int main() {
  std::unique_ptr<controller_base> controller;
  if (/* runtime_condition_for_controller_a == */ true) {
    controller = std::make_unique<controller_a>();
    controller->advance(state{});
    controller->reset();
  }
  if (/* runtime_condition_for_controller_b == */ true) {
    controller = std::make_unique<controller_b>();
    controller->advance(state{});
    controller->reset(); // You can call it but it may not do anything meaningful
  }
}
#+end_src

#+RESULTS:
: controller_a::advance
: controller_a::reset
: controller_b::advance
: controller_b::reset

*** Type erasure




- Type erasure :: Benefits: Value semantics. Drawbacks: Boilerplate.

*** Adding operations

** Static polymorphism

Happens when the program is compiled. Example: Configuring a planner for a robot. VAMP?

*** Adding types

*** Adding operations



** Notes

- Presentation idea: Illustrative but non-idiomatic code snippets in text, links to idiomatic versions on compiler explorer.

- * Satisfying the open-closed principle for both types and operations is called the [[https://en.wikipedia.org/wiki/Expression_problem][Expression Problem]], and there is rich literature on it if you're interested [T][O][D][O].
