#+include: ../elements/title.org
#+include: ../elements/navigation.org

* News

Click the list items to show/hide details.

#+html: <news>
#+html: <details><summary>- <b>Jul 2023</b> Our EELS paper was accepted at IROS.</summary>
The [[https://www-robotics.jpl.nasa.gov/how-we-do-it/systems/exobiology-extant-life-surveyor-eels/][Exobiology Extant Life Surveyor (EELS)]] team wrote a paper that presents control and planning algorithms for EELS. One of the core ideas of the paper is to decouple shape control from motion control for screw-based gaits. This lets us tackle control and planning problems with relatively simple algorithms despite the many (>30) degrees of freedom EELS has.
#+html: </details>

#+html: <details><summary>- <b>Oct 2022</b> I'm now a Robotics Technologist at NASA/JPL.</summary>
I was promoted to Robotics Technologist at JPL. Fortunately my responsibilities stay the same, so I still get to do hands-on robotics work on the [[https://www-robotics.jpl.nasa.gov/how-we-do-it/systems/exobiology-extant-life-surveyor-eels/][Exobiology Extant Life Surveyor (EELS)]] and the [[https://mars.nasa.gov/msr/spacecraft/sample-recovery-helicopters/][Sample Recovery Helicopters (SRH)]] ground mobility effort.
#+html: </details>

#+html: <details><summary>- <b>Aug 2022</b> Wil's TMIT* paper was published at RA-L.</summary>
I coauthored a paper with [[https://scholar.google.com/citations?user=qsIX7joAAAAJ&hl=en][Wil]] and [[https://robotic-esp.com/gammell/][Jon]] that presents Task and Motion Informed Trees (TMIT*), an integrated task and motion planning algorithm. TMIT* combines AIT* with [[https://www.cs.cornell.edu/~wil/papers/isrr2019_unifiedtamp.pdf][PLANET]] to improve performance when high-level tasks, such as sorting potentially stacked objects, require reasoning about the order in which path-planning problems are to be executed.
#+html: </details>

#+html: <details><summary>- <b>Jan 2022</b> I started as a postdoc at NASA/JPL.</summary>
I accepted a position as a postdoctoral researcher at NASA/JPL. I'm part of the autonomy team for a snake-like robot called [[https://www-robotics.jpl.nasa.gov/how-we-do-it/systems/exobiology-extant-life-surveyor-eels/][EELS]] that is being built to explore alien worlds. My work focuses on coming up with path planning and control approaches for EELS and includes contributing to the corresponding modules in its C++ autonomy stack.
#+html: </details>

#+html: <details><summary>- <b>Jan 2022</b> I passed my viva at the University of Oxford!</summary>
I passed my viva (Ph.D. defense) at the University of Oxford. There are umpteen people to thank. Here I just want to thank Jon for letting me stand on his shoulders these past three years and Nick and Wheeler for their time and constructive criticism. It is sincerely appreciated!
#+html: </details>

#+html: <details><summary>- <b>Nov 2021</b> The journal paper on AIT* & EIT* was accepted at IJRR.</summary>
My first journal paper got accepted at IJRR. AIT* and EIT* improve planning performance by leveraging multiple sources of information with an asymmetric bidirectional search. The paper will be published in 2022 but you can already find a preprint [[https://arxiv.org/abs/2111.01877][on arxiv]] and a high-level presentation of it [[https://youtu.be/aC2xBwOcDoo][on youtube]].
#+html: </details>

#+html: <details><summary>- <b>Apr 2021</b> I wrote about heuristics for obstacle clearance.</summary>
Obstacle clearance in search space is an important optimization objective in path planning because it can result in safe paths. This technical report presents admissible heuristics that can improve planning performance when optimizing this objective. You can find the report [[https://arxiv.org/abs/2104.02298][on arxiv]].
#+html: </details>

#+html: <details><summary>- <b>Sep 2020</b> Jon's survey was accepted at ARCRAS.</summary>
I assisted Jon in surveying the field of asymptotically optimal sampling-based path planning algorithms for an invited paper in the /Annual Review of Controls, Robotics, and Autonomous Systems/. The paper will be published in 2021, but you can find a preprint of it [[https://arxiv.org/abs/2002.06599][on arxiv]].
#+html: </details>

#+html: <details><summary>- <b>Aug 2020</b> Mike's paper was accepted at IROS.</summary>
I coauthored a paper that presents the autonomy system used on Axel during the field trial last summer. The autonomy system includes a stability analysis that predicts the interaction of Axel's tether with the terrain. My main contribution was to describe how we adapted ABIT* to work with Axel's tether-induced non-Markovian states. You can find an open-access version of it [[https://robotic-esp.com/papers/paton_iros20.html][on the ESP website]].
#+html: </details>

#+html: <details><summary>- <b>Feb 2020</b> Adaptively Informed Trees (AIT*) was accepted at ICRA.</summary>
My second paper got accepted at ICRA. AIT* improves planning performance with an asymmetric bidirectional search in which both searches continuously inform each other with complementary information. You can find the AIT* paper [[https://arxiv.org/abs/2002.06599][on arxiv]] and a high-level presentation of it [[https://www.youtube.com/watch?v=1h7ugF9F6VM][on youtube]].
#+html: </details>

#+html: <details><summary>- <b>Feb 2020</b> Advanced BIT* (ABIT*) was accepted at ICRA.</summary>
My first paper got accepted at ICRA. ABIT* leverages advanced graph-search techniques, such as inflation and truncation, in sampling-based path planning. This is the algorithm we tested last summer. You can find the ABIT* paper [[https://arxiv.org/abs/2002.06589][on arxiv]] a high-level presentation of it [[https://www.youtube.com/watch?v=ZghEeVGgecY][on youtube]].
#+html: </details>

#+html: <details><summary>- <b>Jul 2019</b> We went on a NASA/JPL field trial in California.</summary>
Jon and I had the chance to join the [[https://www.jpl.nasa.gov/][NASA Jet Propulsion Laboratory (JPL)]] on a [[https://www.youtube.com/watch?v=GUNWVroyys4][field trial for Axel]] in the Mojave Desert. We tested new path planning techniques and supported the team at JPL in running science and autonomy experiments.
#+html: </details>

#+html: <details><summary>- <b>Sep 2018</b> I started my Ph.D. at the University of Oxford.</summary>
I've joined Jon's [[https://robotic-esp.com/][Estimation, Search, and Planning Group]] at the [[https://ori.ox.ac.uk/][Oxford Robotics Institute]] to work on path planning for complex systems.
#+html: </details>

#+html: <details><summary>- <b>Jan 2018</b> We rowed across the Atlantic!</summary>
[[https://www.swissmocean.ch/][Swiss Mocean]] got third place in the 2017 [[https://www.taliskerwhiskyatlanticchallenge.com/][Talisker Whisky Atlantic Challenge]] and became the first Swiss fours to row any ocean. It took us 30 days, 4 hours, and 59 minutes to row from the Canaries to the Caribbean Islands. If your IP is from Switzerland, you can watch a professionally produced documentary about the project [[https://www.srf.ch/play/tv/sendung/rudern-am-limit][here]]. It's in Swiss German, but there's also a version of it with English subtitles [[https://www.youtube.com/playlist?list=PLoxsQMM4ggWFoDgPxYeukqFxZ8K3CPG2n][on youtube]].
#+html: </details>
#+html: </news>
